import numpy as np
import pandas as pd


addresses = ['Shahran', 'Pardis', 'Shahrake Qods', 'Shahrake Gharb',
            'North Program Organization', 'Andisheh', 'West Ferdows Boulevard',
            'Narmak', 'Zafar', 'Islamshahr', 'Pirouzi',
            'Shahrake Shahid Bagheri', 'Moniriyeh', 'Saadat Abad', 'Amirieh',
            'Southern Janatabad', 'Salsabil', 'Zargandeh', 'Feiz Garden',
            'Water Organization', 'ShahrAra', 'Gisha', 'Ray', 'Abbasabad',
            'Ostad Moein', 'Parand', 'Punak', 'Qasr-od-Dasht', 'Aqdasieh',
            'Railway', 'Central Janatabad', 'East Ferdows Boulevard',
            'Pakdasht KhatunAbad', 'Sattarkhan', 'Shahryar',
            'Northern Janatabad', 'Southern Program Organization', 'Rudhen',
            'West Pars', 'Afsarieh', 'Marzdaran', 'Chahardangeh', 'Pakdasht',
            'Baqershahr', 'Jeyhoon', 'Lavizan', 'Shams Abad', 'Fatemi',
            'Keshavarz Boulevard', 'Baghestan', 'Kahrizak', 'Qarchak',
            'Northren Jamalzadeh', 'Azarbaijan', 'Bahar',
            'Persian Gulf Martyrs Lake', 'Beryanak', 'Heshmatieh',
            'Elm-o-Sanat', 'Golestan', 'Shahr-e-Ziba', 'Chardivari', 'Gholhak',
            'Heravi', 'Hashemi', 'Pasdaran', 'Dehkade Olampic', 'Republic',
            'Gheitarieh', 'Qazvin Imamzadeh Hassan', 'Niavaran', 'Valiasr',
            'Amir Bahador', 'Ekhtiarieh', 'Ekbatan', 'Mahallati', 'Ozgol',
            'Tajrish', 'Abazar', 'Parastar', 'Farmanieh', 'Majidieh',
            'Southern Chitgar', 'Si Metri Ji', 'Karoon', 'Northern Chitgar',
            'East Pars', 'Air force', 'Sohanak', 'Kamranieh', 'Komeil', 'Kook',
            'Azadshahr', 'Zibadasht', 'Zaferanieh', 'Amirabad', 'Dorous',
            'Mirdamad', 'Razi', 'Qalandari', 'Jordan', 'Yaftabad', 'Mehran',
            'Nasim Shahr', 'Koohsar', 'Tenant', 'Fallah', 'Eskandari',
            'Shahrakeh Naft', 'Ajudaniye', 'Tehransar', 'Nawab', 'Yousef Abad',
            'Northern Suhrawardi', 'Villa', 'Hakimiyeh', 'Nezamabad',
            'Garden of Saba', 'Tarasht', 'Azari', 'Shahrake Apadana', 'Araj',
            'Malard', 'Shahrake Azadi', 'Darband', 'Tehran Now', 'Dezashib',
            'Darabad', 'Damavand', 'Eram', 'Atabak', 'Sabalan', 'SabaShahr',
            'Shahrake Madaen', 'Waterfall', 'Salehabad', 'Pishva', 'Enghelab',
            'Islamshahr Elahieh', 'Ray - Montazeri', 'Velenjak',
            'Firoozkooh Kuhsar', 'Ghoba', 'Hekmat', 'Shahedshahr', 'Mehrabad',
            'Southern Suhrawardi', 'Abuzar', 'Dolatabad', 'Hor Square',
            'Taslihat', 'Kazemabad', 'Haft Tir', 'Robat Karim',
            'Ray - Pilgosh', 'Ghiyamdasht', 'Elahieh', 'Telecommunication',
            'Mirza Shirazi', 'Karimkhan', 'Seyed Khandan', 'Shahrake Quds',
            'Safadasht', 'Khademabad Garden', 'Hassan Abad', 'Chidz',
            'Sadeghieh', 'Khavaran', 'Boloorsazi', 'Mehrabad River River',
            'Thirteen November', 'Darakeh', 'Aliabad South', 'Alborz Complex',
            'Firoozkooh', 'Vahidiyeh', 'Shadabad', 'Ahang', 'Vahidieh',
            'Mahmoudieh', 'Javadiyeh', 'Yakhchiabad', 'Shoosh', 'Daryan No']
